# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'walkerTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for walkerTracker
pod "Material"
pod 'FontAwesome.swift'
  target 'walkerTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'walkerTrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
